config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :people
  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"

  root :to => "welcome#index"

  namespace :admin do
    resources :events
    root "events#index"
  end

  resources :events do
    resources :attendees
    resource :location, controller: 'event_locations'
    resources :memberships

    collection do
      get :latest
      post :bulk_delete
      post :bulk_update
    end

    member do
      get :dashboard
      # post :join
      # post :withdraw
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  #有Foreign Key的Model，就是設定belongs_to的Model。
  belongs_to :event
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence:true
  has_many :attendees, ->{  order("id DESC") }, dependent: :destroy
  belongs_to :category, optional: true
  has_one :location, dependent: :destroy
  has_many :event_groupships
  has_many :groups, through: :event_groupships
  has_many :memberships
  has_many :users, through: :memberships
  accepts_nested_attributes_for :location, allow_destroy: true, reject_if: :all_blank
end

app/models/event_groupship.rb
class EventGroupship < ApplicationRecord
  belongs_to :event
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :event_groupships
  has_many :events, through: :event_groupships
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :event
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :memberships
  has_many :events, through: :memberships

  def admin?
    self.role == "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :find_event

  def index
    @attendees = @event.attendees
  end

  def show
    @attendee = @event.attendees.find(params[:id])
  end

  def new
    @attendee = @event.attendees.build
  end

  def create
    @attendee = @event.attendees.build(attendee_params)
    if @attendee.save
      redirect_to event_attendees_url(@event)
    else
      render :new
    end
  end

  def edit
    @attendee = @event.attendees.find(params[:id])
  end

  def update
    @attendee = @event.attendees.find(params[:id])

    if @attendee.update(attendee_params)
      redirect_to event_attendees_url(@event)
    else
      render :edit
    end
  end

  def destroy
    @attendee = @event.attendees.find(params[:id])
    @attendee.destroy

    redirect_to event_attendees_url(@event)
  end

private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def attendee_params
    params.require(:attendee).permit(:name)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [ :show, :edit, :update, :destroy, :dashboard]
  
  def index
    if params[:keyword]
      @events = Event.where(["name like?", "%#{params[:keyword]}%"])
    else
      @events = Event.all
      sort_by = (params[:order] == 'name') ? 'name' : 'created_at'
      @events = Event.order(sort_by)
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
      flash[:notice] = "event was successfully created"
    else
      render :new
    end  
  end

  def show
    @page_title = @event.name
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event)
      flash[:notice] = "event was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    flash[:alert] = "event was successfully deleted"
    redirect_to events_path
  end

  def latest
    @events = Event.order("id DESC").limit(3)
  end

  def bulk_delete
    Event.destroy_all
    redirect_to events_path
  end

  def bulk_update
    ids = Array(params[:ids])
    events = ids.map{ |i| Event.find_by_id(i) }.compact
  
    if params[:commit] == "Publish"
      events.each{ |e| e.update( :status => "published" ) }
    elsif params[:commit] == "Delete"
      events.each{ |e| e.destroy }
    end
  
    redirect_to events_url
  end

  def dashboard
  end

  private
  def event_params
    params.require(:event).permit(:name, :description, :category_id,
                                  location_attributes: [:id, :name, :_destroy],
                                  group_ids: [])
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def say
    
  end

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/event_locations_helper.rb
module EventLocationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def setup_event(event)
    event.build_location unless event.location
    event
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attendees/_form.html.erb
<%= form_with model: attendee, url: event_attendee_path(@event,@attendee),method: "patch" do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/attendees/edit.html.erb
<%= form_with model: @attendee, url: event_attendee_path(@event, @attendee),method: :patch  do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/attendees/index.html.erb
<ul>
  <% @attendees.each do |attendee| %>
    <li>
      <%= attendee.name %>
      <%= link_to 'show', event_attendee_path(@event, attendee) %>
      <%= link_to 'edit', edit_event_attendee_path(@event, attendee) %>
      <%= link_to 'destroy', event_attendee_path(@event, attendee), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'new attendee', new_event_attendee_path(@event) %>

app/views/attendees/new.html.erb
<%= form_with model: @attendee, url: event_attendees_path(@event) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/attendees/show.html.erb
<p><%= @attendee.name %> </p>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>